export const metadata = {
  title: 'Backoffice',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <head>
        <meta charSet="utf-8" />git 
        <link rel="icon" href="../../public/img/harp.ico" />
      </head>
      <body>
        {children}
      </body>
    </html>
  )
}
